name: "CI"
on:
  pull_request:
  push:
    branches:
      - "master"
env:
  PHP_EXTENSIONS: "dom, mbstring, xml, bcmath"
  PHP_INI_VALUES: "memory_limit=-1, assert.exception=1, zend.assertions=1, error_reporting=-1, log_errors_max_len=0, display_errors=On"
jobs:
  unit:
    name: "Unit tests ${{matrix.php-version}}-${{matrix.operating-system}}-${{matrix.dependencies}}"
    runs-on: ${{matrix.operating-system}}
    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
          - "windows-latest"
        php-version:
          - "8.0"
        dependencies:
          - "lowest"
          - "highest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{matrix.php-version}}"
          extensions: "${{env.PHP_EXTENSIONS}}"
          ini-values: "${{env.PHP_INI_VALUES}}"
          tools: "composer:v2"
      - name: "Update composer"
        run: "composer self-update"
      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress --no-suggest"
      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress --no-suggest"
      - name: "Execute tests"
        run: "vendor/bin/phpunit --fail-on-warning"
  psalm:
    name: "Psalm"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
        php-version:
          - "8.0"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{matrix.php-version}}"
          extensions: "${{env.PHP_EXTENSIONS}}"
          ini-values: "${{env.PHP_INI_VALUES}}"
          tools: "composer:v2"
      - name: "Update composer"
        run: "composer self-update"
      - name: "Install highest dependencies"
        run: "composer update --no-interaction --no-progress --no-suggest"
      - name: "Execute Psalm"
        run: "vendor/bin/psalm"
  stan:
    name: "PhpStan"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
        php-version:
          - "8.0"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{matrix.php-version}}"
          extensions: "${{env.PHP_EXTENSIONS}}"
          ini-values: "${{env.PHP_INI_VALUES}}"
          tools: "composer:v2"
      - name: "Update composer"
        run: "composer self-update"
      - name: "Install highest dependencies"
        run: "composer update --no-interaction --no-progress --no-suggest"
      - name: "Execute PhpStan"
        run: "composer stan"
  code-style:
    name: "Code style"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
        php-version:
          - "8.0"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{matrix.php-version}}"
          extensions: "${{env.PHP_EXTENSIONS}}"
          ini-values: "${{env.PHP_INI_VALUES}}"
          tools: "composer:v2"
      - name: "Update composer"
        run: "composer self-update"
      - name: "Install highest dependencies"
        run: "composer update --no-interaction --no-progress --no-suggest"
      - name: "Execute PhpCs"
        run: "composer cs"
  security:
    name: "Security check"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        operating-system:
          - "ubuntu-latest"
        php-version:
          - "8.0"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{matrix.php-version}}"
          extensions: "${{env.PHP_EXTENSIONS}}"
          ini-values: "${{env.PHP_INI_VALUES}}"
          tools: "composer:v2"
      - name: "Update composer"
        run: "composer self-update"
      - name: "Install highest dependencies"
        run: "composer update --no-interaction --no-progress --no-suggest"
      - name: "Execute security check"
        run: "composer sec"
